INTERNET_ACCESS: true # Set to true to enable internet access
MAX_SEARCH_RESULTS: 5 # Set the maximum search results for internet access DONT SET TOO HIGH

ALLOW_DM: true # Set to true to allow direct messages
SMART_MENTION: true # Set to true to enable smart mention feature

GPT_MODEL: mixtral-8x7b # Model used for chat >>> gpt-3.5-turbo-1106 , gpt-4-0125-preview

MAX_HISTORY: 50 # Set the maximum message history

PRESENCES_CHANGE_DELAY: 90 # Please note that the Presences Change Delay is measured in seconds. It is advisable not to set it too low, as doing so may result in your bot being rate-limited by Discord
AI_NSFW_CONTENT_FILTER: false # Enable NSFW AI detector to detect NSFW prompt on Imagine Command

LANGUAGE: en # Specify the language code (check 'lang' folder for valid codes)

INSTRUCTIONS: Ada # Specify the instruction prompt to use (check 'instructions' folder for valid prompts)
# To add custom prompts, create a .txt file like 'custom.txt' in `instructions` folder and set INSTRUCTIONS as 'custom'

TRIGGER:
  - chatbot
  - bot nickname
  - bot alias
  - bot name
  - Other bot alias...
  - gpt
# Define the triggers that the bot should always respond to when in message

DISABLE_PRESENCE: false
PRESENCES:
  - Space Engineers
  - tempotary banned from reality
# List of different presences to be used

OCR_MODEL_URLS:
  - "https://api-inference.huggingface.co/models/microsoft/trocr-base-printed"
  - "https://api-inference.huggingface.co/models/nlpconnect/vit-gpt2-image-captioning"
# List of URLs for OCR models

BLACKLIST_WORDS:
  - HACKER
  
# Blacklisted words for /Imagine command this is disabled if you enable AI_NSFW_CONTENT_FILTER
